apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busyboxplus-daemonset
  namespace: mateapp
  labels:
    app: busyboxplus-ds
spec:
  selector:
    matchLabels:
      app: busyboxplus-ds
  template:
    metadata:
      labels:
        app: busyboxplus-ds
    spec:
      containers:
      - name: busyboxplus
        image: ikulyk404/busyboxplus:curl
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        command: ["sh", "-c"]
        args:
          - |
            while true; do
              echo "Checking todoapp service...";
              curl -s http://todoapp.todoapp.svc.cluster.local || echo "Service not reachable";
              sleep 5
            done
        ports:
        - containerPort: 80
